#!/usr/bin/env bash
# clean.sh — strip regenerable files from "kawasan" before air-gapped transfer.
# Generated by Claude Code on 2026-07-11 — REVIEW BEFORE RUNNING.
#
# Default is a DRY-RUN: prints what would be removed, deletes NOTHING.
#   ./clean.sh                       dry-run (safe)
#   ./clean.sh --apply               delete the files listed below
#   ./clean.sh --apply --strip-git   also delete all .git dirs (IRREVERSIBLE:
#                                    local git history is lost — run on a copy!)
set -euo pipefail
cd -- "$(dirname -- "${BASH_SOURCE[0]}")"

APPLY=0
STRIP_GIT=0
for arg in "$@"; do
  case "$arg" in
    --apply)     APPLY=1 ;;
    --strip-git) STRIP_GIT=1 ;;
    -h|--help)   sed -n '2,9p' "$0"; exit 0 ;;
    *)           echo "unknown argument: $arg (use --apply, --strip-git)" >&2; exit 2 ;;
  esac
done

# One-off paths to remove, relative to the project root. Sizes measured 2026-07-11.
TARGETS=(
  "build"   # 511 MB — CMake build tree (CMakeCache, CMakeFiles, object files, test/tool/example binaries, Testing/ logs); regenerate with: cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo && cmake --build build
)

# Names removed recursively across the whole tree (never descends into .git).
FIND_DIR_PATTERNS=(__pycache__)    # e.g. (node_modules dist __pycache__)
FIND_FILE_PATTERNS=(.DS_Store)   # e.g. (.DS_Store "*.log")

TOTAL_KB=0
remove() {
  local path="$1" size_kb
  { [ -e "$path" ] || [ -L "$path" ]; } || return 0
  size_kb=$(du -sk -- "$path" 2>/dev/null | cut -f1) || size_kb=0
  size_kb=${size_kb:-0}
  TOTAL_KB=$((TOTAL_KB + size_kb))
  if [ "$APPLY" -eq 1 ]; then
    rm -rf -- "$path"
    printf 'removed       %9d KB  %s\n' "$size_kb" "$path"
  else
    printf 'would remove  %9d KB  %s\n' "$size_kb" "$path"
  fi
}

for t in ${TARGETS[@]+"${TARGETS[@]}"}; do remove "$t"; done

for pat in ${FIND_DIR_PATTERNS[@]+"${FIND_DIR_PATTERNS[@]}"}; do
  while IFS= read -r -d '' p; do remove "$p"; done \
    < <(find . -name .git -prune -o -type d -name "$pat" -prune -print0)
done
for pat in ${FIND_FILE_PATTERNS[@]+"${FIND_FILE_PATTERNS[@]}"}; do
  while IFS= read -r -d '' p; do remove "$p"; done \
    < <(find . -name .git -prune -o -type f -name "$pat" -print0)
done

if [ "$STRIP_GIT" -eq 1 ]; then
  while IFS= read -r -d '' p; do remove "$p"; done \
    < <(find . -type d -name .git -prune -print0)
fi

if [ "$APPLY" -eq 1 ]; then MODE='freed'; else MODE='would free'; fi
printf '\nkawasan: %s ~%d MB\n' "$MODE" "$((TOTAL_KB / 1024))"
if [ "$APPLY" -eq 0 ]; then
  printf 'Dry-run only — nothing was deleted. Re-run with --apply to delete.\n'
fi
