#include "kawasan/protocol/api_keys.h"

namespace kawasan::protocol {

const char* apiKeyToString(ApiKey key) {
    switch (key) {
        case ApiKey::PRODUCE:
            return "Produce";
        case ApiKey::FETCH:
            return "Fetch";
        case ApiKey::LIST_OFFSETS:
            return "ListOffsets";
        case ApiKey::METADATA:
            return "Metadata";
        case ApiKey::LEADER_AND_ISR:
            return "LeaderAndIsr";
        case ApiKey::STOP_REPLICA:
            return "StopReplica";
        case ApiKey::UPDATE_METADATA:
            return "UpdateMetadata";
        case ApiKey::CONTROLLED_SHUTDOWN:
            return "ControlledShutdown";
        case ApiKey::OFFSET_COMMIT:
            return "OffsetCommit";
        case ApiKey::OFFSET_FETCH:
            return "OffsetFetch";
        case ApiKey::FIND_COORDINATOR:
            return "FindCoordinator";
        case ApiKey::JOIN_GROUP:
            return "JoinGroup";
        case ApiKey::HEARTBEAT:
            return "Heartbeat";
        case ApiKey::LEAVE_GROUP:
            return "LeaveGroup";
        case ApiKey::SYNC_GROUP:
            return "SyncGroup";
        case ApiKey::DESCRIBE_GROUPS:
            return "DescribeGroups";
        case ApiKey::LIST_GROUPS:
            return "ListGroups";
        case ApiKey::SASL_HANDSHAKE:
            return "SaslHandshake";
        case ApiKey::API_VERSIONS:
            return "ApiVersions";
        case ApiKey::CREATE_TOPICS:
            return "CreateTopics";
        case ApiKey::DELETE_TOPICS:
            return "DeleteTopics";
        case ApiKey::DELETE_RECORDS:
            return "DeleteRecords";
        case ApiKey::INIT_PRODUCER_ID:
            return "InitProducerId";
        case ApiKey::OFFSET_FOR_LEADER_EPOCH:
            return "OffsetForLeaderEpoch";
        case ApiKey::ADD_PARTITIONS_TO_TXN:
            return "AddPartitionsToTxn";
        case ApiKey::ADD_OFFSETS_TO_TXN:
            return "AddOffsetsToTxn";
        case ApiKey::END_TXN:
            return "EndTxn";
        case ApiKey::WRITE_TXN_MARKERS:
            return "WriteTxnMarkers";
        case ApiKey::TXN_OFFSET_COMMIT:
            return "TxnOffsetCommit";
        case ApiKey::DESCRIBE_ACLS:
            return "DescribeAcls";
        case ApiKey::CREATE_ACLS:
            return "CreateAcls";
        case ApiKey::DELETE_ACLS:
            return "DeleteAcls";
        case ApiKey::DESCRIBE_CONFIGS:
            return "DescribeConfigs";
        case ApiKey::ALTER_CONFIGS:
            return "AlterConfigs";
        case ApiKey::ALTER_REPLICA_LOG_DIRS:
            return "AlterReplicaLogDirs";
        case ApiKey::DESCRIBE_LOG_DIRS:
            return "DescribeLogDirs";
        case ApiKey::SASL_AUTHENTICATE:
            return "SaslAuthenticate";
        case ApiKey::CREATE_PARTITIONS:
            return "CreatePartitions";
        case ApiKey::CREATE_DELEGATION_TOKEN:
            return "CreateDelegationToken";
        case ApiKey::RENEW_DELEGATION_TOKEN:
            return "RenewDelegationToken";
        case ApiKey::EXPIRE_DELEGATION_TOKEN:
            return "ExpireDelegationToken";
        case ApiKey::DESCRIBE_DELEGATION_TOKEN:
            return "DescribeDelegationToken";
        case ApiKey::DELETE_GROUPS:
            return "DeleteGroups";
        case ApiKey::ELECT_LEADERS:
            return "ElectLeaders";
        case ApiKey::INCREMENTAL_ALTER_CONFIGS:
            return "IncrementalAlterConfigs";
        case ApiKey::ALTER_PARTITION_REASSIGNMENTS:
            return "AlterPartitionReassignments";
        case ApiKey::LIST_PARTITION_REASSIGNMENTS:
            return "ListPartitionReassignments";
        case ApiKey::OFFSET_DELETE:
            return "OffsetDelete";
        case ApiKey::DESCRIBE_CLIENT_QUOTAS:
            return "DescribeClientQuotas";
        case ApiKey::ALTER_CLIENT_QUOTAS:
            return "AlterClientQuotas";
        case ApiKey::DESCRIBE_USER_SCRAM_CREDENTIALS:
            return "DescribeUserScramCredentials";
        case ApiKey::ALTER_USER_SCRAM_CREDENTIALS:
            return "AlterUserScramCredentials";
        case ApiKey::VOTE:
            return "Vote";
        case ApiKey::BEGIN_QUORUM_EPOCH:
            return "BeginQuorumEpoch";
        case ApiKey::END_QUORUM_EPOCH:
            return "EndQuorumEpoch";
        case ApiKey::DESCRIBE_QUORUM:
            return "DescribeQuorum";
        case ApiKey::ALTER_PARTITION:
            return "AlterPartition";
        case ApiKey::UPDATE_FEATURES:
            return "UpdateFeatures";
        case ApiKey::ENVELOPE:
            return "Envelope";
        case ApiKey::FETCH_SNAPSHOT:
            return "FetchSnapshot";
        case ApiKey::DESCRIBE_CLUSTER:
            return "DescribeCluster";
        case ApiKey::DESCRIBE_PRODUCERS:
            return "DescribeProducers";
        case ApiKey::BROKER_REGISTRATION:
            return "BrokerRegistration";
        case ApiKey::BROKER_HEARTBEAT:
            return "BrokerHeartbeat";
        case ApiKey::UNREGISTER_BROKER:
            return "UnregisterBroker";
        case ApiKey::DESCRIBE_TRANSACTIONS:
            return "DescribeTransactions";
        case ApiKey::LIST_TRANSACTIONS:
            return "ListTransactions";
        case ApiKey::ALLOCATE_PRODUCER_IDS:
            return "AllocateProducerIds";
        default:
            return "Unknown";
    }
}

}  // namespace kawasan::protocol

