---
apiVersion: v1
kind: Service
metadata:
  name: kawasan-broker
  labels:
    app: kawasan
    component: broker
spec:
  type: ClusterIP
  selector:
    app: kawasan
    component: broker
  ports:
  - name: kafka
    port: 9092
    targetPort: kafka
    protocol: TCP
  - name: metrics
    port: 9308
    targetPort: metrics
    protocol: TCP
  sessionAffinity: None

---
apiVersion: v1
kind: Service
metadata:
  name: kawasan-broker-headless
  labels:
    app: kawasan
    component: broker
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: kawasan
    component: broker
  ports:
  - name: kafka
    port: 9092
    targetPort: kafka
    protocol: TCP
  publishNotReadyAddresses: true
