#!/bin/bash
# Kawasan Broker Docker Entrypoint Script
# Handles configuration, initialization, and graceful shutdown

set -e

# Color output for logging
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Configuration file paths
CONFIG_FILE="${KAWASAN_CONFIG_FILE:-/etc/kawasan/server.properties}"
TEMPLATE_FILE="/etc/kawasan/server.properties.template"

# Default values
KAWASAN_BROKER_ID="${KAWASAN_BROKER_ID:-0}"
KAWASAN_HOST="${KAWASAN_HOST:-localhost}"
KAWASAN_PORT="${KAWASAN_PORT:-9092}"
KAWASAN_LOG_DIR="${KAWASAN_LOG_DIR:-/var/lib/kawasan/data}"
KAWASAN_LOG_LEVEL="${KAWASAN_LOG_LEVEL:-info}"

# Generate configuration file if it doesn't exist
generate_config() {
    log_info "Generating configuration file at ${CONFIG_FILE}"
    
    if [ ! -f "${CONFIG_FILE}" ]; then
        if [ -f "${TEMPLATE_FILE}" ]; then
            cp "${TEMPLATE_FILE}" "${CONFIG_FILE}"
        else
            log_warn "Template file not found, creating minimal configuration"
            cat > "${CONFIG_FILE}" <<EOF
# Kawasan Broker Configuration (Generated by Docker)
broker.id=${KAWASAN_BROKER_ID}
host=${KAWASAN_HOST}
port=${KAWASAN_PORT}
log.dir=${KAWASAN_LOG_DIR}
log.level=${KAWASAN_LOG_LEVEL}

# Network settings
num.network.threads=${KAWASAN_NUM_NETWORK_THREADS:-3}
num.io.threads=${KAWASAN_NUM_IO_THREADS:-8}

# Socket settings
socket.send.buffer.bytes=${KAWASAN_SOCKET_SEND_BUFFER_BYTES:-102400}
socket.receive.buffer.bytes=${KAWASAN_SOCKET_RECEIVE_BUFFER_BYTES:-102400}
socket.request.max.bytes=${KAWASAN_SOCKET_REQUEST_MAX_BYTES:-104857600}

# Log retention
log.retention.hours=${KAWASAN_LOG_RETENTION_HOURS:-168}
log.segment.bytes=${KAWASAN_LOG_SEGMENT_BYTES:-1073741824}
log.retention.check.interval.ms=${KAWASAN_LOG_RETENTION_CHECK_INTERVAL_MS:-300000}

# Replication
default.replication.factor=${KAWASAN_DEFAULT_REPLICATION_FACTOR:-1}
min.insync.replicas=${KAWASAN_MIN_INSYNC_REPLICAS:-1}
EOF
        fi
    else
        log_info "Configuration file already exists at ${CONFIG_FILE}"
    fi
    
    # Apply environment variable overrides
    apply_env_overrides
}

# Apply environment variable overrides to configuration
apply_env_overrides() {
    log_info "Applying environment variable overrides"
    
    # Override broker.id
    if [ ! -z "${KAWASAN_BROKER_ID}" ]; then
        sed -i "s/^broker\.id=.*/broker.id=${KAWASAN_BROKER_ID}/" "${CONFIG_FILE}" || \
            echo "broker.id=${KAWASAN_BROKER_ID}" >> "${CONFIG_FILE}"
    fi
    
    # Override host
    if [ ! -z "${KAWASAN_HOST}" ]; then
        sed -i "s/^host=.*/host=${KAWASAN_HOST}/" "${CONFIG_FILE}" || \
            echo "host=${KAWASAN_HOST}" >> "${CONFIG_FILE}"
    fi
    
    # Override port
    if [ ! -z "${KAWASAN_PORT}" ]; then
        sed -i "s/^port=.*/port=${KAWASAN_PORT}/" "${CONFIG_FILE}" || \
            echo "port=${KAWASAN_PORT}" >> "${CONFIG_FILE}"
    fi
    
    # Override log directory
    if [ ! -z "${KAWASAN_LOG_DIR}" ]; then
        sed -i "s|^log\.dir=.*|log.dir=${KAWASAN_LOG_DIR}|" "${CONFIG_FILE}" || \
            echo "log.dir=${KAWASAN_LOG_DIR}" >> "${CONFIG_FILE}"
    fi
}

# Initialize data directories
initialize_directories() {
    log_info "Initializing data directories"
    
    # Create log directory if it doesn't exist
    if [ ! -d "${KAWASAN_LOG_DIR}" ]; then
        mkdir -p "${KAWASAN_LOG_DIR}"
        log_info "Created log directory: ${KAWASAN_LOG_DIR}"
    fi
    
    # Ensure proper permissions (already kawasan user in Dockerfile)
    if [ -w "${KAWASAN_LOG_DIR}" ]; then
        log_info "Data directory is writable: ${KAWASAN_LOG_DIR}"
    else
        log_error "Data directory is not writable: ${KAWASAN_LOG_DIR}"
        exit 1
    fi
}

# Validate configuration
validate_config() {
    log_info "Validating configuration"
    
    if [ ! -f "${CONFIG_FILE}" ]; then
        log_error "Configuration file not found: ${CONFIG_FILE}"
        exit 1
    fi
    
    # Check required parameters
    if ! grep -q "^broker\.id=" "${CONFIG_FILE}"; then
        log_error "Missing required parameter: broker.id"
        exit 1
    fi
    
    if ! grep -q "^port=" "${CONFIG_FILE}"; then
        log_error "Missing required parameter: port"
        exit 1
    fi
    
    log_info "Configuration validation passed"
}

# Signal handler for graceful shutdown
graceful_shutdown() {
    log_info "Received shutdown signal, shutting down gracefully..."
    
    if [ ! -z "${BROKER_PID}" ]; then
        log_info "Sending SIGTERM to broker process (PID: ${BROKER_PID})"
        kill -TERM "${BROKER_PID}" 2>/dev/null || true
        
        # Wait for process to terminate (max 30 seconds)
        local count=0
        while kill -0 "${BROKER_PID}" 2>/dev/null; do
            sleep 1
            count=$((count + 1))
            if [ ${count} -ge 30 ]; then
                log_warn "Broker did not stop gracefully, forcing shutdown"
                kill -KILL "${BROKER_PID}" 2>/dev/null || true
                break
            fi
        done
        
        log_info "Broker stopped"
    fi
    
    exit 0
}

# Trap signals for graceful shutdown
trap graceful_shutdown SIGTERM SIGINT SIGQUIT

# Main execution
main() {
    log_info "Starting Kawasan Broker entrypoint script"
    log_info "Broker ID: ${KAWASAN_BROKER_ID}"
    log_info "Host: ${KAWASAN_HOST}"
    log_info "Port: ${KAWASAN_PORT}"
    log_info "Log Directory: ${KAWASAN_LOG_DIR}"
    log_info "Log Level: ${KAWASAN_LOG_LEVEL}"
    
    # Initialize
    initialize_directories
    generate_config
    validate_config
    
    # Display configuration summary
    log_info "Configuration summary:"
    log_info "  Config file: ${CONFIG_FILE}"
    log_info "  Data directory: ${KAWASAN_LOG_DIR}"
    
    # If command is passed, execute it
    if [ "$#" -gt 0 ]; then
        log_info "Executing command: $@"
        
        # If it's the broker command, run it in background to handle signals
        if [ "$1" = "kawasan-broker" ]; then
            exec "$@" &
            BROKER_PID=$!
            log_info "Broker started with PID: ${BROKER_PID}"
            
            # Wait for broker process
            wait ${BROKER_PID}
        else
            # For other commands, just execute them
            exec "$@"
        fi
    else
        log_error "No command specified"
        exit 1
    fi
}

# Run main function
main "$@"
