broker.id=${KAWASAN_BROKER_ID:0}
host=0.0.0.0
advertised.host=${KAWASAN_ADVERTISED_HOST:localhost}
port=${KAWASAN_PORT:9092}
raft.port=9093
log.dirs=${KAWASAN_LOG_DIR:/var/lib/kawasan/data}
monitoring.enabled=true
monitoring.host=0.0.0.0
monitoring.port=9094
log.cleaner.interval.ms=5000
auto.create.topics.enable=true
default.replication.factor=1
min.insync.replicas=1
compatibility.max.api.version.profile=${KAWASAN_COMPAT_API_PROFILE:4.x}
