#!/usr/bin/env python3
"""Generate docs/api_coverage_matrix.md from the broker source.

0B.7: the matrix doc has historically drifted out of sync with reality
(claiming 14/68 APIs while the source registered 18). This script extracts
the actual `supported_api_versions_` table from
``src/broker/kawasan_broker.cpp`` so the doc is regenerable in CI and can
never lie again.

Usage:
    scripts/generate_api_matrix.py [--output docs/api_coverage_matrix.md] [--check]

``--check`` exits non-zero if the on-disk doc differs from generated output
(useful as a CI gate).
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BROKER_CPP = REPO_ROOT / "src" / "broker" / "kawasan_broker.cpp"
API_KEYS_H = REPO_ROOT / "include" / "kawasan" / "protocol" / "api_keys.h"

# Reference (Kafka 4.2 max version per API). Anything not in this map is
# left blank — better to omit than to mislead.
KAFKA_MAX = {
    0: 11, 1: 16, 2: 8, 3: 12, 4: 7, 5: 4, 6: 8, 7: 3,
    8: 9, 9: 9, 10: 4, 11: 9, 12: 4, 13: 5, 14: 5, 15: 5, 16: 5,
    17: 1, 18: 3, 19: 7, 20: 6, 21: 2, 22: 4, 23: 4, 24: 5, 25: 4,
    26: 4, 27: 1, 28: 4, 29: 3, 30: 3, 31: 3, 32: 4, 33: 2, 34: 2,
    35: 4, 36: 2, 37: 3, 42: 2, 43: 2, 44: 1, 47: 0, 56: 0, 60: 1,
    61: 0, 65: 0, 66: 0, 67: 0,
}


def parse_api_keys() -> dict[str, int]:
    """Map ApiKey enum names → integer values from api_keys.h."""
    keys: dict[str, int] = {}
    pattern = re.compile(r"^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(\d+)\s*,?\s*$")
    in_enum = False
    for line in API_KEYS_H.read_text().splitlines():
        if "enum class ApiKey" in line:
            in_enum = True
            continue
        if in_enum:
            if "}" in line:
                break
            m = pattern.match(line)
            if m:
                keys[m.group(1)] = int(m.group(2))
    return keys


def parse_supported_versions(enum_to_key: dict[str, int]) -> list[tuple[int, str, int, int]]:
    """Parse the supported_api_versions_ initializer in kawasan_broker.cpp.

    Returns (key_id, name, min_version, max_version) tuples in source order.
    """
    source = BROKER_CPP.read_text()
    # Find the supported_api_versions_ initializer block.
    start_marker = "supported_api_versions_ = {"
    start = source.find(start_marker)
    if start < 0:
        sys.exit("ERROR: could not find supported_api_versions_ initializer")
    end = source.find("};", start)
    block = source[start:end]

    # Two forms in the source:
    #   {protocol::ApiKey::FOO, 0, 4},
    #   {protocol::ApiKey::FOO, kFooMaxVersion, kFooMaxVersion},
    # We also need the named-constant values, which are at the top of the file.
    constants = {}
    const_pattern = re.compile(r"constexpr\s+int16_t\s+(\w+)\s*=\s*(\d+)\s*;")
    for m in const_pattern.finditer(source[:start]):
        constants[m.group(1)] = int(m.group(2))

    line_pattern = re.compile(
        r"\{protocol::ApiKey::(\w+),\s*([\w\d]+),\s*([\w\d]+)\}"
    )
    out: list[tuple[int, str, int, int]] = []
    for m in line_pattern.finditer(block):
        name = m.group(1)
        min_raw, max_raw = m.group(2), m.group(3)
        try:
            mn = int(min_raw) if min_raw.isdigit() else constants[min_raw]
        except KeyError:
            sys.exit(f"ERROR: unknown constant {min_raw!r} for {name}")
        try:
            mx = int(max_raw) if max_raw.isdigit() else constants[max_raw]
        except KeyError:
            sys.exit(f"ERROR: unknown constant {max_raw!r} for {name}")
        key_id = enum_to_key.get(name, -1)
        if key_id < 0:
            sys.exit(f"ERROR: ApiKey::{name} not in api_keys.h enum")
        out.append((key_id, name, mn, mx))
    out.sort(key=lambda t: t[0])
    return out


def render(supported: list[tuple[int, str, int, int]], all_keys: dict[str, int]) -> str:
    lines = [
        "# Kawasan API Coverage Matrix",
        "",
        "**Auto-generated by `scripts/generate_api_matrix.py`** from",
        "`src/broker/kawasan_broker.cpp`. Do not edit by hand; rerun the script",
        "(or rely on the `compat-smoke` CI job) to refresh.",
        "",
        f"Total Kafka APIs: **{len(all_keys)}**.",
        f"Currently advertised by Kawasan: **{len(supported)}**.",
        "",
        "## Implemented (advertised in ApiVersions)",
        "",
        "| Key | API | Kawasan range | Kafka 4.2 max |",
        "|----:|-----|:---:|:---:|",
    ]
    supported_ids = {key_id for key_id, *_ in supported}
    for key_id, name, mn, mx in supported:
        kafka_max = KAFKA_MAX.get(key_id, "")
        kafka_max_cell = str(kafka_max) if kafka_max != "" else "—"
        lines.append(f"| {key_id} | `{name}` | {mn}–{mx} | {kafka_max_cell} |")
    lines.append("")
    lines.append("## Absent (returns `UNSUPPORTED_VERSION`)")
    lines.append("")
    lines.append("| Key | API | Kafka 4.2 max |")
    lines.append("|----:|-----|:---:|")
    missing = sorted([(v, k) for k, v in all_keys.items() if v not in supported_ids])
    for key_id, name in missing:
        kafka_max = KAFKA_MAX.get(key_id, "")
        kafka_max_cell = str(kafka_max) if kafka_max != "" else "—"
        lines.append(f"| {key_id} | `{name}` | {kafka_max_cell} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=REPO_ROOT / "docs" / "api_coverage_matrix.md",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if on-disk doc differs from generated content",
    )
    args = parser.parse_args()

    keys = parse_api_keys()
    supported = parse_supported_versions(keys)
    rendered = render(supported, keys)

    if args.check:
        existing = args.output.read_text() if args.output.exists() else ""
        if existing != rendered:
            sys.stderr.write(
                f"FAIL: {args.output} is out of date. "
                f"Run `scripts/generate_api_matrix.py` to regenerate.\n"
            )
            return 1
        return 0

    args.output.write_text(rendered)
    print(f"Wrote {args.output} ({len(supported)} APIs advertised)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
